#!/bin/bash

# this is to parse the @custom_include statements in Tweak.x
# in order to achieve hooks spread up into multiple files.

# read the file line by line and save everything back to Tweak.x
# except for the @custom_include statements, which will be replaced

echo "generating code ..."

read -r -d '' fileheader << MEOW
/*
* !! THIS FILE IS AUTOGENERATED !!
*  DO NOT EDIT, YOUR CHANGES WILL BE OVERWRITTEN
*/
MEOW

function codegen {
    echo "running codegen for $1"
    echo "$fileheader" > ".gen_$1"
    
    while read line; do
        if [[ $line == @custom_include* ]]; then
            file=${line#*@custom_include }
            file=${file%\"*}
            file=${file#\"*}

            echo "found custom include for $file"
            if [ -f "$file" ]; then
                echo "including $file"
                line=$(cat "$file")
            else
                echo "file $file not found"
                exit 1
            fi
        fi

        echo "$line" >> ".gen_$1"
    done < "$1"
}

codegen Tweak.x